import type { Metadata } from "next";

import "./globals.css";

import { ToastContainer } from 'react-toastify';

import { ListActiveThemes } from "@/components/themes/list-active-themes";
import { ThemeContext, ThemeContextProvider } from '@/contexts/theme-context';

export const metadata: Metadata = {
  title: "Treinador com AI",
  description: "Generated by Rodrigo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className="flex flex-col h-screen">
        {/* Header */}
        <header className="bg-blue-600 text-white p-4 flex justify-between items-center">
          <div>
            <a href="/">Treinador com AI</a>
          </div>
        </header>

        <ThemeContextProvider>
          <div className="flex flex-1 flex-row overflow-hidden">
            {/* Menu */}
            <nav className="bg-gray-200 w-64 p-4 flex-shrink-0">
              <b>Menu</b><br />
              <a href="/" className="text-sm">Dashboard</a><br />
              --------------------------------
              <b>Assuntos</b>&nbsp;<a href="/themes/create-theme">(+)</a><br />
              <div className="text-sm">
                <ListActiveThemes />
              </div>
            </nav>

            {/* Content */}
            <div className="flex-1 overflow-auto p-4">
              <ToastContainer />
              {children}
            </div>
          </div>
        </ThemeContextProvider>

        {/* Footer */}
        <footer className="bg-gray-600 text-white p-4 text-center">
          <div>Footer</div>
        </footer>
      </body>
    </html>
  );
}
